import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { type DiscoveredRoute, discoverToolRoutes } from "./discover";

type NitroModuleHooks = { hook: (name: string, fn: () => void | Promise<void>) => void };

type NitroLike = {
  options: {
    rootDir: string;
    srcDir: string;
    buildDir: string;
    handlers: Array<{ route: string; method?: string; handler: string }>;
  };
  hooks: NitroModuleHooks;
};

export type NitroBotModuleOptions = {
  configFile?: string;
};

export default function nitroBotModule(options: NitroBotModuleOptions = {}) {
  return async (nitro: NitroLike) => {
    const rootDir = nitro.options.rootDir;
    const srcDir = nitro.options.srcDir ?? rootDir;
    const buildDir = nitro.options.buildDir ?? resolve(rootDir, ".nitro");
    const routesDir = resolve(srcDir, "routes");
    const configFile = resolve(rootDir, options.configFile ?? "chat.config.ts");

    const routes = await discoverToolRoutes(routesDir);
    if (routes.length === 0) {
      console.warn("[nitro-bot] No routes with `export const definition = tool(...)` found in", routesDir);
    }

    const endpoint = await readEndpoint(configFile);
    const handlerFile = await writeHandlerFile({ buildDir, routes, configFile });

    nitro.options.handlers.push({ route: endpoint, method: "post", handler: handlerFile });

    nitro.hooks.hook("compiled", () => {
      console.log(`[nitro-bot] ${routes.length} tool(s) mounted at POST ${endpoint}`);
    });
  };
}

async function readEndpoint(configFile: string): Promise<string> {
  if (!existsSync(configFile)) return "/chat";
  try {
    const { createJiti } = await import("jiti");
    const jiti = createJiti(configFile, { interopDefault: true });
    const mod = (await jiti.import(configFile)) as { default?: { endpoint?: string }; endpoint?: string };
    const config = mod.default ?? mod;
    return config.endpoint ?? "/chat";
  } catch (error) {
    console.warn("[nitro-bot] Failed to load", configFile, "— falling back to /chat.", error);
    return "/chat";
  }
}

type WriteOptions = {
  buildDir: string;
  routes: DiscoveredRoute[];
  configFile: string;
};

async function writeHandlerFile({ buildDir, routes, configFile }: WriteOptions): Promise<string> {
  const dir = resolve(buildDir, "nitro-bot");
  await mkdir(dir, { recursive: true });
  const handlerFile = resolve(dir, "chat-handler.ts");

  const imports = routes
    .map((route, index) => `import * as r${index} from ${JSON.stringify(route.absPath)};`)
    .join("\n");

  const toolList = routes
    .map(
      (route, index) =>
        `  { method: ${JSON.stringify(route.method)}, path: ${JSON.stringify(route.path)}, module: r${index} }`,
    )
    .join(",\n");

  const configImport = existsSync(configFile)
    ? `import userConfig from ${JSON.stringify(configFile)};`
    : `const userConfig = {};`;

  const source = `// Generated by @elumixor/nitro-bot — do not edit.
import { createChatHandler } from "@elumixor/nitro-bot";
${configImport}
${imports}

const config = (userConfig && typeof userConfig === "object" && "default" in (userConfig as object))
  ? (userConfig as { default: Record<string, unknown> }).default
  : (userConfig as Record<string, unknown>);

export default createChatHandler({
  ...(config as Record<string, unknown>),
  tools: [
${toolList}
  ],
});
`;

  await writeFile(handlerFile, source, "utf8");
  return handlerFile;
}
